const data = [
  {
    name: "The Intelligent Investor: Value Investing",
    image: "https://images-na.ssl-images-amazon.com/images/I/91+t0Di07FL.jpg",
    author: "Benjamin Graham",
    publisher: "Harper Business; 2011th edition",
    publishYear: "1 January 2003",
    price: 584,
    discount: 10,
    deliveryCharge: 80,
    inStock: true,
    fastDelivery: true,
    ratings: "4.5",
    offer: "Best Seller",
    description:
      "The greatest investment advisor of the twentieth century, Benjamin Graham taught and inspired people worldwide. Graham's philosophy of value investing -- which shields investors from substantial error and teaches them to develop long-term strategies -- has made The Intelligent Investor the stock market bible ever since its original publication in 1949. Over the years, market developments have proven the wisdom of Graham's strategies. While preserving the integrity of Graham's original text, this revised edition includes updated commentary by noted financial journalist Jason Zweig, whose perspective incorporates the realities of today's market, draws parallels between Graham's examples and today's financial headlines, and gives readers a more thorough understanding of how to apply Graham's principles. Vital and indispensable, this HarperBusiness Essentials edition of The Intelligent Investor is the most important book you will ever read on how to reach your financial goals.",
    format: "PaperBack",
    asins: "0062312685",
    language: "English",
    pages: 623,
    weight: 580,
    bestSellersRank: "#31 in Books",
  },
  {
    name: "The Psychology of Money (2020)",
    image: "https://images-na.ssl-images-amazon.com/images/I/81cpDaCJJCL.jpg",
    author: "Morgan Housel",
    publisher: "‎ Jaico Publishing House",
    publishYear: "1 September 2020",
    price: 202,
    discount: 10,
    deliveryCharge: 0,
    inStock: true,
    fastDelivery: false,
    ratings: "4.6",
    offer: "Trending",
    description:
      "Timeless lessons on wealth, greed, and happiness doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people. How to manage money, invest it, and make business decisions are typically considered to involve a lot of mathematical calculations, where data and formulae tell us exactly what to do. But in the real world, people don’t make financial decisions on a spreadsheet. They make them at the dinner table, or in a meeting room, where personal history, your unique view of the world, ego, pride, marketing, and odd incentives are scrambled together. In the psychology of money, the author shares 19 short stories exploring the strange ways people think about money and teaches you how to make better sense of one of life’s most important matters.",
    format: "PaperBack",
    asins: "9390166268",
    language: "English",
    pages: 252,
    weight: 220,
    bestSellersRank: "#1 in Books",
  },
  {
    name: "Atomic Habits: Tiny Changes Remarkable results",
    image: "https://images-na.ssl-images-amazon.com/images/I/91bYsX41DVL.jpg",
    author: "James Clear",
    publisher: "‎‎ Random House Business Books",
    publishYear: "11 April 2017",
    price: 420,
    discount: 5,
    deliveryCharge: 0,
    inStock: true,
    fastDelivery: false,
    ratings: "4.4",
    offer: "Best Seller",
    description:
      "A supremely practical and useful book. James Clear distils the most fundamental information about habit formation, so you can accomplish more by focusing on less.’ Mark Manson, author of The Subtle Art of Not Giving A F*ck. ‘James Clear has spent years honing the art and studying the science of habits. This engaging, hands-on book is the guide you need to break bad routines and make good ones.’ Adam Grant, author of Originals.‘A special book that will change how you approach your day and live your life.’ Ryan Holiday, author of The Obstacle is the Way",
    format: "Paperback",
    asins: "1847941834",
    language: "English",
    pages: 388,
    weight: 290,
    bestSellersRank: "#2 in Books",
  },
  {
    name: "Rich Dad Poor Dad:Rich about Money",
    image: "https://images-na.ssl-images-amazon.com/images/I/81dQwQlmAXL.jpg",
    author: "Robert T. Kiyosaki",
    publisher: "‎ Plata Publishing; Second edition",
    publishYear: "11 April 2017",
    price: 2000,
    discount: 13,
    deliveryCharge: 80,
    inStock: true,
    fastDelivery: true,
    ratings: "4.4",
    offer: "",
    description:
      "It's been nearly 25 years since Robert Kiyosaki’s Rich Dad Poor Dad first made waves in the Personal Finance arena.It has since become the #1 Personal Finance book of all time... translated into dozens of languages and sold around the world.Rich Dad Poor Dad is Robert's story of growing up with two dads — his real father and the father of his best friend, his rich dad — and the ways in which both men shaped his thoughts about money and investing. The book explodes the myth that you need to earn a high income to be rich and explains the difference between working for money and having your money work for you.",
    format: "HardCover",
    asins: "1612680194",
    language: "English",
    pages: 336,
    weight: 204,
    bestSellersRank: "#4 in Books",
  },
  {
    name: "How To Win Friend And Influence People",
    image: "https://images-na.ssl-images-amazon.com/images/I/81ixRxn+JKL.jpg",
    author: "Dale Carnegie",
    publisher: "‎‎Pushpak Publictions",
    publishYear: "1 January 2018",
    price: 124,
    discount: 0,
    deliveryCharge: 90,
    inStock: true,
    fastDelivery: false,
    ratings: "4.3",
    offer: "",
    description:
      "Reading books is a kind of enjoyment. Reading books is a good habit. We bring you a different kinds of books. You can carry this book where ever you want. It is easy to carry. It can be an ideal gift to yourself and to your loved ones. Care instruction keep away from fire.",
    format: "Paperback",
    asins: "9382449108",
    language: "English",
    pages: 256,
    weight: 180,
    bestSellersRank: "#303 in Books",
  },
  {
    name: "Romancing The Balance Sheet-Second",
    image: "https://images-na.ssl-images-amazon.com/images/I/71TZUJjoMAL.jpg",
    author: "Dr Anil Lamba",
    publisher: "Collins",
    publishYear: "23 August 2016",
    price: 1410,
    discount: 15,
    deliveryCharge: 0,
    inStock: true,
    fastDelivery: false,
    ratings: "4.2",
    offer: "Commerce",
    description:
      "In this book you will learn that there is no such thing as a non-Finance person. It's a misconception that Finance Management happens in the Finance Department. In fact, it is happening right through the organization.There is a direct relationship between every action you take and the bottom line of your organization. This book will help you to discover and strengthen that relationship.Understand here what Profit really means. If Balance Sheets mystify you, these lucid truths will give you clarity. Learn the rules of Good Financial Management which will keep you secure. Make the most efficient use of your Working Capital, and understand how an increase in Sales actually impacts your Profit. Learn also the simple secrets of Marginal Costing, Leverage and Funds Flow.",
    format: "HardCover",
    asins: "9350294311",
    language: "English",
    pages: 260,
    weight: 744,
    bestSellersRank: "#1542 in Books",
  },
  {
    name: "The Almanack of Naval Ravikant",
    image: "https://images-na.ssl-images-amazon.com/images/I/61XmBlL1N5L.jpg",
    author: "Eric Jorgenson",
    publisher: "Magrathea Publishing",
    publishYear: "15 September 2020",
    price: 1964,
    discount: 3,
    deliveryCharge: 0,
    inStock: true,
    fastDelivery: true,
    ratings: "4.0",
    offer: "",
    description:
      "Getting rich is not just about luck; happiness is not just a trait we are born with. These aspirations may seem out of reach, but building wealth and being happy are skills we can learn.  So what are these skills, and how do we learn them? What are the principles that should guide our efforts? What does progress really look like? Naval Ravikant is an entrepreneur, philosopher, and investor who has captivated the world with his principles for building wealth and creating long-term happiness. The Almanack of Naval Ravikant is a collection of Naval's wisdom and experience from the last ten years, shared as a curation of his most insightful interviews and poignant reflections. This isn't a how-to book, or a step-by-step gimmick. Instead, through Naval's own words, you will learn how to walk your own unique path toward a happier, wealthier life.",
    format: "HardCover",
    asins: "1544514212",
    language: "English",
    pages: 242,
    weight: 313,
    bestSellersRank: "#99 in Books",
  },
  {
    name: "Financial Affairs Of The Common Man",
    image: "https://images-na.ssl-images-amazon.com/images/I/81yqQtWl7EL.jpg",
    author: "Anil Lamba",
    publisher: "Penguin Portfolio",
    publishYear: "9 September 2019",
    price: 564,
    discount: 0,
    deliveryCharge: 70,
    inStock: false,
    fastDelivery: false,
    ratings: "4.3",
    offer: "",
    description:
      "Financial Affairs of the Common Man presents a collage of the various aspects of personal finance management that every individual should pay heed to. It introduces the concepts that you must understand to effectively plan your finances, and provides the tools and the knowledge needed to do so. Read this book, written with the common man in mind using easy-to-understand language, to understand the power of compounding and the effects of inflation on investments. It's time to familiarize yourself with mutual funds and SIPs, and to gain a deeper insight into the making of personal balance sheets and income tax provisions.",
    format: "HardCover",
    asins: "0670090735",
    language: "English",
    pages: 304,
    weight: 300,
    bestSellersRank: "#31,220 in Books",
  },
  {
    name: "Rich Dad's Guide to Investing (2011)",
    image: "https://images-na.ssl-images-amazon.com/images/I/71oRnjdbkjL.jpg",
    author: "Robert T. Kiyosaki",
    publisher: "Perseus Books Group",
    publishYear: "15 September 2011",
    price: 599,
    discount: 17,
    deliveryCharge: 65,
    inStock: true,
    fastDelivery: false,
    ratings: "4.3",
    offer: "Finance",
    description:
      "Rich Dad's Guide to Investing is a roadmap for those who want to become successful investors and invest in the types of assets that the rich do. Whether your goal is to become financially secure, comfortable, or rich this book is your guide to understanding the asset classes and investment strategy. Robert explains his basic rules of investing, how to reduce your risk and Rich Dad's 10 Investor Controls as well as ways to convert your earned income into passive portfolio income.",
    format: "HardCover",
    asins: "1612680216",
    language: "English",
    pages: 316,
    weight: 386,
    bestSellersRank: "#4377 in Books",
  },
  {
    name: "Coffee Can Investing (2018)",
    image: "https://images-na.ssl-images-amazon.com/images/I/81wr8n5+vhL.jpg",
    author: "Saurabh Mukherjea",
    publisher: "Penguin Portfolio",
    publishYear: "23 February 2018",
    price: 317,
    discount: 0,
    deliveryCharge: 110,
    inStock: false,
    fastDelivery: false,
    ratings: "4.5",
    offer: "Best Seller",
    description:
      "Most people invest in the usual assets: real estate, gold, mutual funds, fixed deposits and stock markets. It's always the same four or five instruments. All they end up making is a measly 8 to 12 per cent per annum. Those who are exceptionally unfortunate get stuck in the middle of a crash and end up losing a lot of money.What if there was another way? What if you could make not 10 not 15 but 20 per cent compound annual growth rate (CAGR) on your investments? What if there was a way to grow your money four to five times whilst taking half the risk compared to the overall market?",
    format: "HardCover",
    asins: "9780670090457",
    language: "English",
    pages: 288,
    weight: 295,
    bestSellersRank: "#85 in Books",
  },
  {
    name: "ONE UP ON WALL STREET )",
    image: "https://images-na.ssl-images-amazon.com/images/I/71yvRsuzkiL.jpg",
    author: "Peter Lynch",
    publisher: "SIMON & SCHUSTER USA",
    publishYear: "01 February 2018",
    price: 1601,
    discount: 13,
    deliveryCharge: 0,
    inStock: true,
    fastDelivery: false,
    ratings: "4.0",
    offer: "",
    description:
      "Penned by the famous mutual-fund manager, Peter Lynch, this book elaborates the many advantages that an average investor has over professionals and how they can help them reach financial triumph. How To Use What You Already Know To Make Money in The Market explains how your knowledge alone can assist you beat the pros of investing. From the viewpoint of America's most triumphant money manager, investment chances are extensively accessible. Whether supermarket or work place, you can find goods and services everywhere. You have to select these organizations in which to invest, before they are found by skilled analysts. You will find more interesting knowledge on investment. Thus the book has become one of the best seller and treasure among readers. Moreover, this book provides time less recommendation on money business. This book has discussed the tips, ebb and flows on building it big in the investment market.",
    format: "HardCover",
    asins: "0743200403",
    language: "English",
    pages: 304,
    weight: 279,
    bestSellersRank: "#1477 in Books",
  },
];

module.exports = data;
